config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :users do
  	member do
  		post :confirm_user
  	end
  end
  devise_for :admins
  resources :admins, :only => [:show, :edit, :update ]
  mount Ckeditor::Engine => '/ckeditor'
  root to: "posts#index"
  resources :posts
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 def active_for_authentication? 
    super && approved? 
  end 
  
  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  #This validates presence of title, and makes sure that the length is not more than 140 words
  validates :title, presence: true, length: {maximum: 140}
  #This validates presence of body
  validates :body, presence: true
  def self.search(search)
  	 where("body LIKE ?", "%#{search}%" )
  	 where("title LIKE ?", "%#{search}%")
   end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
 def index
    
    #other alternatives are

    # flash[:warn ] = "Israel don't quite like warnings"

    #flash[:danger ] = "Naomi let the dog out!"
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:edit, :update, :show, :delete]
	before_action :authenticate_admin!, except: [:index, :show]

	# Index action to render all posts
	def index
		@posts = Post.all
		if params[:search]
    		@posts = Post.search(params[:search]).order("created_at DESC")
  		else
    		@posts = Post.all.order('created_at DESC')
  		end
	end

	# New action for creating post
	def new
		@post = Post.new
	end

	# Create action saves the post into database
	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "Successfully created post!"
			redirect_to post_path(@post)
		else
			flash[:alert] = "Error creating new post!"
			render :new
		end
	end

	# Edit action retrives the post and renders the edit page
	def edit
	end

	# Update action updates the post with the new information
	def update 
		
		if @post.update_attributes(post_params)
			redirect_to post_path(@post) 
			# redirect_to(:action => 'posts#show') 
		else 
			flash[:alert] = "Error updating post!"
			render 'edit' 
		end 
	end

	# The show action renders the individual post after retrieving the the id
	def show
	end

	# The destroy action removes the post permanently from the database
	def destroy
		@post = Post.find(params[:id])
    	@post.delete
    	redirect_to :back
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    	if params[:approved] == "false"
      		@admins = Admin.where(approved: false)
    	else
      		@admins = Admin.all
    	end
  	end
	def confirm_user
	    @admins = Admin.find(params[:id])
    	@admins.update_attributes!(approved: true)
      redirect_to :back
	end
	def show
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/_form.html.erb
<%= simple_form_for(@about) do |f| %>
	<% if @about.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@about.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @about.erros.full_messages.each do |msg| %>
          <li>
            <%= mgs %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

	<div class="form-group">
		<%= f.input :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<header class="header" style="color:white;margin-top:-20px;padding-bottom:300px;background-image: url('/images/bg.jpg');background-position: center;-webkit-background-size: cover">
<%= favicon_link_tag '/images/favicon.ico' %>
      <div class="container text-center">        
            <div class="col-sm-offset-1 col-sm-10">
              <div class="site-heading">
                   <script src="https://use.fontawesome.com/57a1cd7064.js"></script>
              </div>
            </div>
          </div>
        
    </header>

<%= link_to 'New About', new_about_path %>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<header class="header" style="color:white;margin-top:-20px;padding-bottom:300px;background-image: url('/images/bg2.jpg');background-position: center;-webkit-background-size: cover">
	<div class="container text-center">        
    	<div class="col-sm-offset-1 col-sm-10">
        	<div class="site-heading">
             </div>
		</div>
    </div>        
</header>
<div class="col-sm-6 col-sm-offset-3 col-xs-12">
  <h2 class="text-center"><%= @about.title %></h2>
  <div><%= raw @about.body %></div>
<% if admin_signed_in? %>
		<%= link_to "Edit", edit_about_path(@about), class: "btn btn-default" %>

  <% end %>

</div>

 <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-12 text-center">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                
              </li>
            </ul>
            <a href="https://www.xing.com/profile/David_Wegener3?sc_o=mxb_p"><i class="fa fa-xing-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="https://www.linkedin.com/in/david-wegener-0bb263100/"><i class="fa fa-linkedin-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="  https://github.com/wegeneda"><i class="fa fa-github-square fa-2x" style="color:#333333" aria-hidden="false"></i></a>
            <p class="copyright text-muted">Copyright &copy;2017 wepunkt CMS on rails</p>
          </div>
        </div>
      </div>
    </footer>

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
 
  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse ">
  <div class="col-sm-offset-1 col-sm-10 container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" style="color:white;font-size: 1.7" href="/"> <span class="glyphicon glyphicon-education" aria-hidden="true"></span> 
       WEPUNKT</a><a class="navbar-brand" style="color:white;font-size: 1.7em;font-weight:bold;letter-spacing: -1px" href="/"></span>BLOG</a>       
    </div>
    <div class="col-sm-3 col-md-3">
        <form class="navbar-form" role="search">
        <%= form_tag(posts_path, :method => "get", id: "search-form", class:"form-control") do %>
            <div class="input-group">
                <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:"form-control" %>
               <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    <% end %>
                 </div>
           </div>
        </form>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'The blogger',  "/abouts/2" %></li>
            <li><%= link_to 'The blog',  "/abouts/1"  %></li>
            <li><a href="#"></a></li>
          </ul>
        </li>

        <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My Account', edit_admin_registration_path  %></li>
            <li><%= link_to 'Manage Users', "/users"  %></li>
        </ul>
        </li>
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Log in', new_admin_session_path  %></li>
            <li><%= link_to 'Sign up', new_admin_registration_path  %></li>
            <li><a href="#"></a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Forgot password', new_admin_password_path  %></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


            
            
    
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WepunktBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "layouts/navigation" %>
<% unless flash.blank? %>
<div class='row'>
  <div class='col-sm-12' style="margin-top:-20px;"">
    <div id='flash'>
      <% flash.each do |key, value| %>
        <div class='flash alert alert-dismissible fade in alert-<%= key == 'notice' ? 'info' : 'danger' %>'>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
            <span aria-hidden='true'>&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>




  <div class="container-fluid">
    <%= yield %>
  </div>


</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.erros.full_messages.each do |msg| %>
          <li>
            <%= mgs %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

	<div class="form-group">
		<%= f.input :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<header class="header" style="color:white;margin-top:-20px;padding-bottom:300px;background-image: url('/images/bg.jpg');background-position: center;-webkit-background-size: cover">
      <%= favicon_link_tag '/images/favicon.ico' %>
      <div class="container text-center">        
            <div class="col-sm-offset-1 col-sm-10">
              <div class="site-heading">
                    <script src="https://use.fontawesome.com/57a1cd7064.js"></script>
              </div>
            </div>
          </div>
        
    </header>


 <div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12">
    <% @posts.reverse.each do |post| %>
    <div class="col-xs-12 text-center">
      <div class="text-center">         
        <h2><%= post.title %></h2>
        <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
      </div>
      <div>
        <%= raw(post.body).truncate(358) %>
      </div>
      <div class="text-center">
        <%= link_to "READ MORE", post_path(post) %>
      </div>
      <% if admin_signed_in? %>
        <%= link_to "Show", post_path(post), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>
      <hr />
    </div>
    <% end %>
  </div>
</div>
 <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-12 text-center">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                
              </li>
            </ul>
            <a href="https://www.xing.com/profile/David_Wegener3?sc_o=mxb_p"><i class="fa fa-xing-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="https://www.linkedin.com/in/david-wegener-0bb263100/"><i class="fa fa-linkedin-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="  https://github.com/wegeneda"><i class="fa fa-github-square fa-2x" style="color:#333333" aria-hidden="false"></i></a>
            <p class="copyright text-muted">Copyright &copy;2017 wepunkt CMS on rails</p>
          </div>
        </div>
      </div>
    </footer>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<%= favicon_link_tag '/images/favicon.ico' %>
<div class="col-sm-6 col-sm-offset-3 col-xs-12">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @post.body %></div>
  <div id="disqus_thread"></div>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <% if admin_signed_in? %>
        
        <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(@post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
 <% end %>
	<script>
	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = 'https://wepunkt.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>

</div>




 <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-12 text-center">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                
              </li>
            </ul>
            <a href="https://www.xing.com/profile/David_Wegener3?sc_o=mxb_p"><i class="fa fa-xing-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="https://www.linkedin.com/in/david-wegener-0bb263100/"><i class="fa fa-linkedin-square fa-2x" style="color:#333333" aria-hidden="false"></i></a> <a href="  https://github.com/wegeneda"><i class="fa fa-github-square fa-2x" style="color:#333333" aria-hidden="false"></i></a>
            <p class="copyright text-muted">Copyright &copy;2017 wepunkt CMS on rails</p>
          </div>
        </div>
      </div>
    </footer>

app/views/users/index.html.erb
<% if admin_signed_in? %>
  <h1>Users</h1>
  <%= link_to "All Users", :action => "index" %>
  |
  <%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>
  <table>
    <% @admins.each do |admin| %>
      <tr>
        <td>
          <%= admin.email %>
        </td>
        <td>
          <%= admin.approved %>
        </td>
        <td>
          <%= form_tag :controller=> 'users', :action=> 'confirm_user', :id => admin.id, :method => :post do  %>
          <%= submit_tag 'Accept user', class: "btn btn-success" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  This page is admin protected
<% end %>